# Generated by Django 2.2.8 on 2020-02-26 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_chatroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.CreateModel(
            name='UsersChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('chat_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_chat_room', to='base.ChatRoom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_chat_room', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_chat_room',
                'unique_together': {('user', 'chat_room')},
            },
        ),
    ]
